name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        ruby: [ '3.1' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Install Linux x86_64-linux
        if: matrix.os == 'ubuntu-20.04'
        shell: bash
        run: |
          gem install asherah --pre
          gem which asherah

      - name: Install Linux aarch64-linux
        if: matrix.os == 'ubuntu-20.04'
        shell: bash
        run: |
          git clone https://github.com/godaddy/asherah-ruby.git
          cd asherah-ruby
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v "$(pwd):/asherah-ruby" --platform=linux/arm64/v8 \
            ruby:${{matrix.ruby}} \
            /bin/sh -c "cd /asherah-ruby; bundle install; gem install asherah --pre; gem which asherah; ruby spec/smoke_test.rb"

      - name: Install Darwin x86_64-darwin
        if: matrix.os == 'macos-11'
        shell: bash
        run: |
          gem install asherah --pre
          gem which asherah
